import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Frontend Developer | GudoFabi",
    template: "%s | GudoFabi",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <h1>Header</h1>
        </header>
        <div id="main-content">{children}</div>
        <footer
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
